#pragma once

#include <session/config/namespaces.hpp>
#include <session/sodium_array.hpp>
#include <session/sqlite.hpp>
#include <session/types.hpp>

#include "core/callbacks.hpp"
#include "core/devices.hpp"
#include "core/globals.hpp"
#include "core/pro.hpp"

/// The "Core" class is intended to be used by a Session account instance to hold account state.  It
/// manages an encrypted sqlite database for storing account keys, messages, and other account
/// state.
///
/// This class is currently in an early state with only partial database, but this class is intended
/// to eventually grow to the point where it contains the entire data model of a Session account
/// (i.e.  conversations, contacts, messages, etc.) and manages that data (e.g. by fetching data
/// from swarms).
///
/// Currently Core does not yet have its own network stack and so the integrating application must
/// update the Core instance when it receives the appropriate data (such as pro revocations) from
/// the network.
///
/// The typical intended flow for using the Core is to construct it early in the application and
/// store it for the application duration:
///
///     session::core::Core core{
///         std::filesystem::path{"/path/to/libsession.db"},
///         session::sqlite::argon2id_password{"user-supplied password"}
///     };
///
/// (Or keep it in a unique or shared ptr if you have more complex ownership needs).
///
/// The above examples shows a usage where the database is:
/// - encrypted using AEGIS-256
/// - encrypted using a password resulting from argon2id password hashing
/// - is fully encrypted, with the first 16 bytes of the file containing the password salt.
///
/// The above can be modified to pass any of the options supported by session::sqlite::Database, but
/// some of the most common ones are depicted here.
///
/// If you have secure storage of a 32 byte secure random value (for example, 32 bytes generated by
/// libsodium's randombytes_buf) then instead of the argon2id_password argument you can pass a
/// raw_key:
///
///     session::core::Core core{
///         std::filesystem::path{"/path/to/libsession.db"},
///         session::sqlite::raw_key{key}
///     };
///
/// If you have such a raw key that you can keep secure, this will open the database substantially
/// faster than needing to perform an argon2id hash.  DO NOT use this approach with a user-supplied
/// password.
///
/// (Note that the above makes a secure copy when opening the database.  If you cannot avoid making
/// a copy yourself, remember to copy into at least a `session::cleared_uc32` or use similar secure
/// clearing after use to ensure the key bytes does not remain in unused process memory).
///
/// If you want password protection instead of secure raw key protection then replace
///
///     session::sqlite::raw_key{key}
///
/// with
///
///     session::sqlite::argon2id_password{user_pass}
///
/// You can optionally crank up the argon2 settings for a more secure (but slower to open) database
/// by adding additional arguments to the argon2id_password constructor; see the session-sqlite
/// documentation for details.
///
/// For iOS, where full encryption causes the OS to kill the process but opens up a magic special
/// snowflake exception if it thinks your file is SQLite, you can pass an extra argument value:
///
///     session::sqlite::plaintext_header
///
/// which will cause the initial 24 bytes of the file to be unencrypted, allowing the file to pass
/// iOS's sniff test to get magic permissions.  Note that if you combine this with argon2id_password
/// you must also create and store a session::sqlite::salt value and pass that every time the
/// database is opened.  The salt should be random bytes generated by a cryptographically secure
/// RNG, but can be stored without encryption once generated (i.e. it is not a sensitive value).
///
/// Example construction:
///
/// ```C++
/// #include <session/core.hpp>
/// #include <session/sqlite.hpp>
///
/// int main() {
///
///     session::core::Core core{
///         std::filesystem::path{"/path/to/libsession.db"},
///         session::sqlite::argon2id_password{"correct horse battery staple"}
///     };
///
///     run_my_app(core);
/// }
///
///
///     // Later on somewhere deep inside `run_my_app` when an updated revocation list is received:
///     try {
///         core.pro.update_revocations(...);
///     } catch (const std::exception& e) {
///         log::warning(cat, "Failed to update Pro revocation list: {}", e.what());
///     }
///
///     // When checking to verify a Pro account proof:
///     if (!core.pro.proof_is_revoked(...)) {
///         // bro is Pro!
///     }
///
/// ```

namespace oxen::quic {
class Loop;
}  // namespace oxen::quic

namespace session::pro_backend {
struct ProRevocationItem;
};  // namespace session::pro_backend

namespace session::core {

namespace quic = oxen::quic;

namespace detail {
    class CoreComponent;
}

class Core {
    // Constructed first (in init()), destroyed last: must outlive all components that use it.
    // Custom deleter allows quic::Loop to remain an incomplete type in this header.
    struct LoopDeleter {
        void operator()(quic::Loop*) const;
    };
    std::unique_ptr<quic::Loop, LoopDeleter> _loop;

    sqlite::Database db;
    friend class detail::CoreComponent;

    core::callbacks callbacks;

    // Called during the constructor: the database is opened and all members are constructed, but
    // `init()` hasn't called called yet.
    void apply_migrations();

    std::list<detail::CoreComponent*> _comp_init;
    void register_comp_init(detail::CoreComponent* c);

    // Performs the non-templated part of Core construction: this executes any needed database
    // migrations, and then calls init() on each sub-component.
    void init();

  public:
    // Constructor taking a struct of callbacks to invoke on various events, and any number of
    // session::SQLite database options to open the core database.
    template <sqlite::DatabaseOption... DBOpts>
    Core(core::callbacks callbacks, std::filesystem::path db_path, const DBOpts&... opts) :
            callbacks{std::move(callbacks)}, db{std::move(db_path), opts...} {
        init();
    }

    // Global value storage.  This are used by some components, but can also be used by the
    // application to persist settings.
    Globals globals{*this};

    // Session Pro-related capabilities
    Pro pro{*this};

    // Device groups for handling shared encryption key among account devices
    Devices devices{*this};

    // Passes a batch of messages retrieved from the swarm to the appropriate handler based on the
    // namespace they were retrieved from.  `is_final` should be true if this batch represents the
    // complete current contents of the namespace (i.e. there are no more messages pending
    // retrieval), and false if more messages may follow.  Note that if there turn out to be no more
    // messages after a non-final call, the caller should still call this with an empty span and
    // is_final=true to flush any actions that are deferred until the end of a fetch.
    void receive_messages(
            std::span<const std::span<const unsigned char>> messages,
            config::Namespace ns,
            bool is_final);
};

}  // namespace session::core
