#pragma once

#include <chrono>
#include <session/types.hpp>
#include <string>

namespace session::pro_backend {

/// TODO: Assign the Session Pro backend public key for verifying proofs to allow users of the
/// library to have the pubkey available for verifying proofs.
constexpr array_uc32 PUBKEY = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                               0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                               0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static_assert(sizeof(PUBKEY) == array_uc32{}.size());

struct ResponseHeader {
    /// Status code: RESPONSE_STATUS_SUCCESS for success, other values indicate errors
    std::uint32_t status;

    /// List of parsing or processing errors. Empty if there are no parsing errors, if there are
    /// errors, the parse may be partially complete, always check the errors before proceeding.
    std::vector<std::string> errors;
};

struct MasterRotatingSignatures {
    array_uc64 master_sig;
    array_uc64 rotating_sig;
};

/// Register a new Session Pro proof to the backend. The payment is registered under the
/// `master_pkey` and authorises the `rotating_pkey` to use the proof. In practice this means that
/// the caller will receive a Session Pro Proof that can be attached to messages that have to be
/// signed by the `rotating_pkey` for other clients to entitle that message to Pro privileges.
///
/// The attached signatures must sign over the contents of the request which can be generated by the
/// helper function `build_sigs`.
struct AddProPaymentRequest {
    /// Request version. The latest accepted version is 0
    std::uint8_t version;

    /// 32-byte Ed25519 Session Pro master public key derived from the Session account seed to
    /// register a Session Pro payment under.
    array_uc32 master_pkey;

    /// 32-byte Ed25519 Session Pro rotating public key to authorise to use the generated Session
    /// Pro proof
    array_uc32 rotating_pkey;

    /// 32-byte payment token hash from a third-party store proving purchase of a subscription
    array_uc32 payment_token;

    /// 64-byte signature proving knowledge of the master key's secret component
    array_uc64 master_sig;

    /// 64-byte signature proving knowledge of the rotating key's secret component
    array_uc64 rotating_sig;

    /// API: pro/AddProPaymentRequest::to_json
    ///
    /// Serializes the request to a JSON string.
    ///
    /// Outputs:
    /// - `std::string` - JSON representation of the request.
    std::string to_json() const;

    /// API: pro/AddProPaymentRequest::build_sigs
    ///
    /// Builds the master and rotating signatures using the provided private keys and payment token
    /// hash. Throws if the keys (32-byte or 64-byte libsodium format) or 32-byte payment token hash
    /// are passed with an incorrect size. Using 64-byte libsodium keys is more efficient.
    ///
    /// Inputs:
    /// - `request_version` -- Version of the request to build a hash for
    /// - `master_privkey` -- 64-byte libsodium style or 32 byte Ed25519 master private key
    /// - `rotating_privkey` -- 64-byte libsodium style or 32 byte Ed25519 rotating private key
    /// - `payment_token_hash` -- 32-byte hash of the payment token.
    /// - `unix_ts` -- Unix timestamp (seconds) for the request.
    ///
    /// Outputs:
    /// - `MasterRotatingSignatures` - Struct containing the 64-byte master and rotating signatures.
    static MasterRotatingSignatures build_sigs(
            std::uint8_t request_version,
            std::span<const uint8_t> master_privkey,
            std::span<const uint8_t> rotating_privkey,
            std::span<const uint8_t> payment_token_hash,
            std::chrono::sys_seconds unix_ts);
};

/// The generated proof from the Session Pro backend that has been parsed from JSON. This structure
/// is the raw parse result that can then be converted into the config::ProProof or equivalent
/// structure.
struct AddProPaymentOrGetProProofResponse : public ResponseHeader {
    /// Unix timestamp (seconds) of when the proof expires
    std::chrono::sys_seconds expiry_unix_ts;

    /// 32-byte hash of the internal generation index shared across all proofs generated under the
    /// same group of payments
    array_uc32 gen_index_hash;

    /// 32-byte Ed25519 Session Pro rotating public key authorized to use the proof
    array_uc32 rotating_pkey;

    /// 64-byte signature by the Session Pro backend to allow other clients to validate that the
    /// proof was issued by an authoritative backend.
    array_uc64 sig;

    /// API: pro/AddProPaymentOrGetProProofResponse::parse
    ///
    /// Parses a JSON string into the response struct.
    ///
    /// Inputs:
    /// - `json` -- JSON string to parse.
    ///
    /// Outputs:
    /// - `bool` - True if parsing succeeds, false otherwise. Errors are stored in `errors`.
    bool parse(std::string_view json);
};

/// Request a new Session Pro proof from the backend. The specified `master_pkey` must have
/// previously already registered a payment to the backend that is still active and hence entitled
/// to Session Pro features. This endpoint can then be used to pair a new Ed25519 key to be
/// authorised to use a the Session Pro proof.
struct GetProProofRequest {
    /// Request version. The latest accepted version is 0
    std::uint8_t version;

    /// 32-byte Ed25519 Session Pro master public key to generate a Session Pro proof from. This key
    /// must have had a prior, and still active payment registered under it for a new proof to be
    /// generated successfully.
    array_uc32 master_pkey;

    /// 32-byte Ed25519 Session Pro rotating public key authorized to use the generated proof
    array_uc32 rotating_pkey;

    /// Unix timestamp (seconds) of the request
    std::chrono::seconds unix_ts;

    /// 64-byte signature proving knowledge of the master key's secret component
    array_uc64 master_sig;

    /// 64-byte signature proving knowledge of the rotating key's secret component
    array_uc64 rotating_sig;

    /// API: pro/MasterRotatingSignatures::build_sigs
    ///
    /// Builds master and rotating signatures using the provided private keys and timestamp.
    /// Throws if the keys (32-byte or 64-byte libsodium format) are incorrectly sized.
    /// Using 64-byte libsodium keys is more efficient.
    ///
    /// Inputs:
    /// - `request_version` -- Version of the request to build a hash for
    /// - `master_privkey` -- 64-byte libsodium style or 32 byte Ed25519 master private key
    /// - `rotating_privkey` -- 64-byte libsodium style or 32 byte Ed25519 rotating private key
    /// - `unix_ts` -- Unix timestamp (seconds) for the request.
    ///
    /// Outputs:
    /// - `MasterRotatingSignatures` - Struct containing the 64-byte master and rotating signatures.
    static MasterRotatingSignatures build_sigs(
            std::uint8_t request_version,
            std::span<const uint8_t> master_privkey,
            std::span<const uint8_t> rotating_privkey,
            std::chrono::seconds unix_ts);

    /// API: pro/GetProProofRequest::to_json
    ///
    /// Serializes the request to a JSON string.
    ///
    /// Outputs:
    /// - `std::string` - JSON representation of the request.
    std::string to_json() const;
};

/// Retrieve the current list of revocations for currently active Session Pro proofs (because of
/// refunds for example). The caller should maintain this list until the revocation has expired and
/// periodically retrieve this list from the backend every hour.
struct GetProRevocationsRequest {
    /// Request version. The latest accepted version is 0
    std::uint8_t version;

    /// 4-byte monotonic integer for the caller's revocation list iteration. Set to 0 if unknown;
    /// otherwise, use the latest known `ticket` from a prior `GetProRevocationResponse` to allow
    /// the Session Pro Backend to omit the revocation list if it has not changed.
    std::uint32_t ticket;

    /// API: pro/GetProProofRequest::to_json
    ///
    /// Serializes the request to a JSON string.
    ///
    /// Outputs:
    /// - `std::string` - JSON representation of the request.
    std::string to_json() const;
};

struct ProRevocationItem {
    /// 32-byte hash of the generation index, identifying a proof
    array_uc32 gen_index_hash;

    /// Unix timestamp (seconds) when the proof expires
    std::chrono::sys_seconds expiry_unix_ts;
};

struct GetProRevocationsResponse : public ResponseHeader {
    /// 4-byte monotonic integer for the latest revocation list iteration.
    /// Update the caller's ticket to this value for subsequent requests.
    std::uint32_t ticket;

    /// List of revoked Session Pro proofs
    std::vector<ProRevocationItem> items;

    /// API: pro/GetProRevocationsResponse::parse
    ///
    /// Parses a JSON string into the response struct.
    ///
    /// Inputs:
    /// - `json` -- JSON string to parse.
    ///
    /// Outputs:
    /// - `bool` - True if parsing succeeds, false otherwise. Errors are stored in `errors`.
    bool parse(std::string_view json);
};

struct GetProPaymentsRequest {
    /// Request version for the API
    std::uint8_t version;

    /// 32-byte Ed25519 master public key to retrieve payments for
    array_uc32 master_pkey;

    /// 64-byte signature proving knowledge of the master public key's secret component
    array_uc64 master_sig;

    /// Unix timestamp (seconds) of the request
    std::chrono::sys_seconds unix_ts;

    /// Page number for paginated API requests
    std::uint32_t page;

    /// API: pro/GetProProofRequest::to_json
    ///
    /// Serializes the request to a JSON string.
    ///
    /// Outputs:
    /// - `std::string` - JSON representation of the request.
    std::string to_json() const;
};

struct ProPaymentItem {
    /// Unix timestamp (seconds) when the payment was activated for Session Pro.
    /// 0 if not activated (e.g., another active subscription or refunded).
    std::chrono::sys_seconds activation_unix_ts;

    /// Unix timestamp (seconds) when the payment was archived (e.g., refunded or revoked).
    /// 0 if not archived.
    std::chrono::sys_seconds archive_unix_ts;

    /// Unix timestamp (seconds) of payment registration, rounded to the next day
    std::chrono::sys_seconds creation_unix_ts;

    /// Subscription duration in seconds
    std::chrono::seconds subscription_duration;

    /// 32-byte hash of the payment token
    array_uc32 payment_token_hash;
};

struct GetProPaymentsResponse : public ResponseHeader {
    /// List of payment items for the master public key
    std::vector<ProPaymentItem> items;

    /// Total pages available in the paginated API
    std::uint32_t pages;

    /// Total payments for the user (active, refunded, or non-active)
    std::uint32_t payments;

    /// API: pro/GetProPaymentsResponse::parse
    ///
    /// Parses a JSON string into the response struct.
    ///
    /// Inputs:
    /// - `json` -- JSON string to parse.
    ///
    /// Outputs:
    /// - `bool` - True if parsing succeeds, false otherwise. Errors are stored in `errors`.
    bool parse(std::string_view json);
};
}  // namespace session::pro_backend
