#pragma once

#include <session/pro_backend.h>

#include <chrono>
#include <session/session_protocol.hpp>
#include <session/types.hpp>
#include <span>
#include <string>

/// Helper functions to construct payloads to communicate with the Session Pro Backend. The data
/// structures here are largely bindings to the endpoints exposed on the Session Pro Backend:
///
///   github.com/Doy-lee/session-pro-backend/blob/2afe310adad52f211e3b2cfcbdfc9eda6ff1778e/server.py#L24
///
/// The high level summary of the functionality in this file. Clients can:
///
/// 1. Build a request with `AddProPaymentRequest::to_json` from a Session Pro payment and submit it
///    to the backend to register the specified Ed25519 keys for Session Pro.
///
///    Server responds JSON to be parsed with `GetProPaymentsRequest::parse`. Clients should
///    validate the response and update their `UserProfile` by constructing a `ProConfig` with the
///    proof from the response by using `ProProof::from_pro_backend_response()` and filling in the
///    relevant private key that the proof was authorised for.
///
///    The server will only respond successfully if it can also independently verify the purchase
///    otherwise an error is returned and can be read from the `ResponseHeader` after parsing the
///    raw response.
///
/// 2. Attach the `ProProof` constructed from (1) into their messages. Libsession has helper
///    functions to embed the proof into their messages via the helper functions in the Session
///    Protocol header file.
///
/// 3. Periodically poll the global revocation list which overrides the validity of current
///    circulating proofs. This is done by constructing the request via
///    `GetProRevocationsRequest::to_json` and sending it to the backend.
///
///    Server responds JSON to be parsed with `GetProRevocationResponse::parse` which contains the
///    list that clients should cache. Any incoming messages with a Pro proof that is in the list of
///    revoked proofs will not be entitled to Pro features.
///
/// 4. Query the list of historical payments that the master Ed25519 key has registered by building
///    a `GetProPaymentsRequest::to_json` query and submitting it.
///
///    Server responds JSON to be parsed with `GetProPaymentsResponse::parse` which they can use to
///    populate their client's payment history.
///
/// 5. Get a list of per-payment provider URLs, such as links to the support page for refunds and
///    subscription via the `PAYMENT_PROVIDER_METADATA` global variable defined in the C header.
///
/// See the unit tests for examples of using the APIs mentioned.

namespace session::pro_backend {

/// TODO: Assign the Session Pro backend public key for verifying proofs to allow users of the
/// library to have the pubkey available for verifying proofs.
constexpr array_uc32 PUBKEY = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                               0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                               0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
static_assert(sizeof(PUBKEY) == array_uc32{}.size());

struct ResponseHeader {
    /// Status code: RESPONSE_STATUS_SUCCESS for success, other values indicate errors
    std::uint32_t status;

    /// List of parsing or processing errors. Empty if there are no parsing errors, if there are
    /// errors, the parse may be partially complete, always check the errors before proceeding.
    std::vector<std::string> errors;
};

struct MasterRotatingSignatures {
    array_uc64 master_sig;
    array_uc64 rotating_sig;
};

struct AddProPaymentUserTransaction {
    SESSION_PRO_BACKEND_PAYMENT_PROVIDER provider;
    std::string payment_id;
};

/// Register a new Session Pro proof to the backend. The payment is registered under the
/// `master_pkey` and authorises the `rotating_pkey` to use the proof. In practice this means that
/// the caller will receive a Session Pro Proof that can be attached to messages that have to be
/// signed by the `rotating_pkey` for other clients to entitle that message to Pro privileges.
///
/// The attached signatures must sign over the contents of the request which can be generated by the
/// helper function `build_sigs`.
struct AddProPaymentRequest {
    /// Request version. The latest accepted version is 0
    std::uint8_t version;

    /// 32-byte Ed25519 Session Pro master public key derived from the Session account seed to
    /// register a Session Pro payment under.
    array_uc32 master_pkey;

    /// 32-byte Ed25519 Session Pro rotating public key to authorise to use the generated Session
    /// Pro proof
    array_uc32 rotating_pkey;

    /// Transaction containing the payment details to register on the Session Pro backend
    AddProPaymentUserTransaction payment_tx;

    /// 64-byte signature proving knowledge of the master key's secret component
    array_uc64 master_sig;

    /// 64-byte signature proving knowledge of the rotating key's secret component
    array_uc64 rotating_sig;

    /// API: pro/AddProPaymentRequest::to_json
    ///
    /// Serializes the request to a JSON string.
    ///
    /// Outputs:
    /// - `std::string` - JSON representation of the request.
    std::string to_json() const;

    /// API: pro/AddProPaymentRequest::build_sigs
    ///
    /// Builds the master and rotating signatures using the provided private keys and payment token
    /// hash. Throws if the keys (32-byte or 64-byte libsodium format) or 32-byte payment token hash
    /// are passed with an incorrect size. Using 64-byte libsodium keys is more efficient.
    ///
    /// Inputs:
    /// - `request_version` -- Version of the request to build a hash for
    /// - `master_privkey` -- 64-byte libsodium style or 32 byte Ed25519 master private key
    /// - `rotating_privkey` -- 64-byte libsodium style or 32 byte Ed25519 rotating private key
    /// - `payment_token_hash` -- 32-byte hash of the payment token.
    ///
    /// Outputs:
    /// - `MasterRotatingSignatures` - Struct containing the 64-byte master and rotating signatures.
    static MasterRotatingSignatures build_sigs(
            std::uint8_t request_version,
            std::span<const uint8_t> master_privkey,
            std::span<const uint8_t> rotating_privkey,
            SESSION_PRO_BACKEND_PAYMENT_PROVIDER payment_tx_provider,
            std::span<const uint8_t> payment_tx_payment_id);
};

/// The generated proof from the Session Pro backend that has been parsed from JSON. This structure
/// is the raw parse result that can then be converted into the config::ProProof or equivalent
/// structure.
struct AddProPaymentOrGetProProofResponse : public ResponseHeader {
    ProProof proof;

    /// API: pro/AddProPaymentOrGetProProofResponse::parse
    ///
    /// Parses a JSON string into the response struct.
    ///
    /// Inputs:
    /// - `json` -- JSON string to parse.
    ///
    /// Outputs:
    /// - `bool` - True if parsing succeeds, false otherwise. Errors are stored in `errors`.
    static AddProPaymentOrGetProProofResponse parse(std::string_view json);
};

/// Request a new Session Pro proof from the backend. The specified `master_pkey` must have
/// previously already registered a payment to the backend that is still active and hence entitled
/// to Session Pro features. This endpoint can then be used to pair a new Ed25519 key to be
/// authorised to use a the Session Pro proof.
struct GetProProofRequest {
    /// Request version. The latest accepted version is 0
    std::uint8_t version;

    /// 32-byte Ed25519 Session Pro master public key to generate a Session Pro proof from. This key
    /// must have had a prior, and still active payment registered under it for a new proof to be
    /// generated successfully.
    array_uc32 master_pkey;

    /// 32-byte Ed25519 Session Pro rotating public key authorized to use the generated proof
    array_uc32 rotating_pkey;

    /// Unix timestamp (seconds) of the request
    std::chrono::seconds unix_ts;

    /// 64-byte signature proving knowledge of the master key's secret component
    array_uc64 master_sig;

    /// 64-byte signature proving knowledge of the rotating key's secret component
    array_uc64 rotating_sig;

    /// API: pro/MasterRotatingSignatures::build_sigs
    ///
    /// Builds master and rotating signatures using the provided private keys and timestamp.
    /// Throws if the keys (32-byte or 64-byte libsodium format) are incorrectly sized.
    /// Using 64-byte libsodium keys is more efficient.
    ///
    /// Inputs:
    /// - `request_version` -- Version of the request to build a hash for
    /// - `master_privkey` -- 64-byte libsodium style or 32 byte Ed25519 master private key
    /// - `rotating_privkey` -- 64-byte libsodium style or 32 byte Ed25519 rotating private key
    /// - `unix_ts` -- Unix timestamp (seconds) for the request.
    ///
    /// Outputs:
    /// - `MasterRotatingSignatures` - Struct containing the 64-byte master and rotating signatures.
    static MasterRotatingSignatures build_sigs(
            std::uint8_t request_version,
            std::span<const uint8_t> master_privkey,
            std::span<const uint8_t> rotating_privkey,
            std::chrono::seconds unix_ts);

    /// API: pro/GetProProofRequest::to_json
    ///
    /// Serializes the request to a JSON string.
    ///
    /// Outputs:
    /// - `std::string` - JSON representation of the request.
    std::string to_json() const;
};

/// Retrieve the current list of revocations for currently active Session Pro proofs (because of
/// refunds for example). The caller should maintain this list until the revocation has expired and
/// periodically retrieve this list from the backend every hour.
struct GetProRevocationsRequest {
    /// Request version. The latest accepted version is 0
    std::uint8_t version;

    /// 4-byte monotonic integer for the caller's revocation list iteration. Set to 0 if unknown;
    /// otherwise, use the latest known `ticket` from a prior `GetProRevocationResponse` to allow
    /// the Session Pro Backend to omit the revocation list if it has not changed.
    std::uint32_t ticket;

    /// API: pro/GetProProofRequest::to_json
    ///
    /// Serializes the request to a JSON string.
    ///
    /// Outputs:
    /// - `std::string` - JSON representation of the request.
    std::string to_json() const;
};

struct ProRevocationItem {
    /// 32-byte hash of the generation index, identifying a proof
    array_uc32 gen_index_hash;

    /// Unix timestamp (seconds) when the proof expires
    std::chrono::sys_seconds expiry_unix_ts;
};

struct GetProRevocationsResponse : public ResponseHeader {
    /// 4-byte monotonic integer for the latest revocation list iteration.
    /// Update the caller's ticket to this value for subsequent requests.
    std::uint32_t ticket;

    /// List of revoked Session Pro proofs
    std::vector<ProRevocationItem> items;

    /// API: pro/GetProRevocationsResponse::parse
    ///
    /// Parses a JSON string into the response struct.
    ///
    /// Inputs:
    /// - `json` -- JSON string to parse.
    ///
    /// Outputs:
    /// - `bool` - True if parsing succeeds, false otherwise. Errors are stored in `errors`.
    static GetProRevocationsResponse parse(std::string_view json);
};

struct GetProPaymentsRequest {
    /// Request version for the API
    std::uint8_t version;

    /// 32-byte Ed25519 master public key to retrieve payments for
    array_uc32 master_pkey;

    /// 64-byte signature proving knowledge of the master public key's secret component
    array_uc64 master_sig;

    /// Unix timestamp (seconds) of the request
    std::chrono::sys_seconds unix_ts;

    /// Page number for paginated API requests
    std::uint32_t page;

    /// API: pro/AddProPaymentRequest::build_sigs
    ///
    /// Builds the master and rotating signatures using the provided private keys and payment token
    /// hash. Throws if the keys (32-byte or 64-byte libsodium format) or 32-byte payment token hash
    /// are passed with an incorrect size. Using 64-byte libsodium keys is more efficient.
    ///
    /// Inputs:
    /// - `request_version` -- Version of the request to build a hash for
    /// - `master_privkey` -- 64-byte libsodium style or 32 byte Ed25519 master private key
    /// - `unix_ts` -- Unix timestamp (seconds) for the request.
    /// - `page` -- The page in the paginated list of historical payments to request
    ///
    /// Outputs:
    /// - `array_uc64` - the 64-byte signature
    static array_uc64 build_sig(
            uint8_t version,
            std::span<const uint8_t> master_privkey,
            std::chrono::sys_seconds unix_ts,
            uint32_t page);

    /// API: pro/GetProProofRequest::to_json
    ///
    /// Serializes the request to a JSON string.
    ///
    /// Outputs:
    /// - `std::string` - JSON representation of the request.
    std::string to_json() const;
};

struct ProPaymentItem {
    /// Describes the current status of the consumption of the payment for Session Pro entitlement
    SESSION_PRO_BACKEND_PAYMENT_STATUS status;

    /// Unix timestamp (seconds) when the payment was activated for Session Pro.
    /// 0 if not activated (e.g., another active subscription or refunded).
    std::chrono::sys_seconds activated_unix_ts;

    /// Unix timestamp (seconds) when the payment was expired. 0 if not activated
    std::chrono::sys_seconds expired_unix_ts;

    /// Unix timestamp (seconds) when the payment was redeemed. 0 if not activated
    std::chrono::sys_seconds redeemed_unix_ts;

    /// Unix timestamp (seconds) when the payment was refunded. 0 if not activated
    std::chrono::sys_seconds refunded_unix_ts;

    /// Subscription duration in seconds
    std::chrono::seconds subscription_duration;

    /// Store front that this particular payment came from
    SESSION_PRO_BACKEND_PAYMENT_PROVIDER payment_provider;

    /// When payment provider is set to Google Play Store, this is the platform-specific purchase
    /// token
    std::string google_payment_token;

    /// When payment provider is set to iOS App Store, this is the platform-specific original
    /// transaction ID
    std::string apple_original_tx_id;

    /// When payment provider is set to iOS App Store, this is the platform-specific transaction ID
    std::string apple_tx_id;

    /// When payment provider is set to iOS App Store, this is the platform-specific web line order
    /// ID
    std::string apple_web_line_order_id;
};

struct GetProPaymentsResponse : public ResponseHeader {
    /// List of payment items for the master public key
    std::vector<ProPaymentItem> items;

    /// Total pages available in the paginated API
    std::uint32_t pages;

    /// Total payments for the user (active, refunded, or non-active)
    std::uint32_t payments;

    /// API: pro/GetProPaymentsResponse::parse
    ///
    /// Parses a JSON string into the response struct.
    ///
    /// Inputs:
    /// - `json` -- JSON string to parse.
    ///
    /// Outputs:
    /// - `bool` - True if parsing succeeds, false otherwise. Errors are stored in `errors`.
    static GetProPaymentsResponse parse(std::string_view json);
};

void make_blake2b32_hasher(struct crypto_generichash_blake2b_state* hasher);
}  // namespace session::pro_backend
