#pragma once

typedef enum CONVO_NOTIFY_MODE {
    CONVO_NOTIFY_DEFAULT = 0,
    CONVO_NOTIFY_ALL = 1,
    CONVO_NOTIFY_DISABLED = 2,
    CONVO_NOTIFY_MENTIONS_ONLY = 3,
} CONVO_NOTIFY_MODE;

typedef enum CLIENT_NOTIFY_CONTENT {
    CLIENT_NOTIFY_CONTENT_DEFAULT = 0,
    CLIENT_NOTIFY_CONTENT_NAME_AND_PREVIEW = 1,
    CLIENT_NOTIFY_CONTENT_NAME_NO_PREVIEW = 2,
    CLIENT_NOTIFY_CONTENT_NO_NAME_NO_PREVIEW = 3,
} CLIENT_NOTIFY_CONTENT;
