#pragma once

typedef enum CLIENT_THEME {
    CLIENT_THEME_DEFAULT = 0,
    CLIENT_THEME_CLASSIC_DARK = 1,
    CLIENT_THEME_CLASSIC_LIGHT = 2,
    CLIENT_THEME_OCEAN_DARK = 3,
    CLIENT_THEME_OCEAN_LIGHT = 4,
} CLIENT_THEME;

typedef enum CLIENT_THEME_PRIMARY_COLOR {
    CLIENT_THEME_PRIMARY_COLOR_DEFAULT = 0,
    CLIENT_THEME_PRIMARY_COLOR_GREEN = 1,
    CLIENT_THEME_PRIMARY_COLOR_BLUE = 2,
    CLIENT_THEME_PRIMARY_COLOR_YELLOW = 3,
    CLIENT_THEME_PRIMARY_COLOR_PINK = 4,
    CLIENT_THEME_PRIMARY_COLOR_PURPLE = 5,
    CLIENT_THEME_PRIMARY_COLOR_ORANGE = 6,
    CLIENT_THEME_PRIMARY_COLOR_RED = 7,
} CLIENT_THEME_PRIMARY_COLOR;
