-- Cache filenames are keyed now (see `cache::name_for`), so every name derived under the old
-- unkeyed scheme names a file nothing will ever look for again: a lookup computes the new name,
-- misses, and downloads afresh.  The rows would meanwhile go on counting towards the cache limit,
-- evicting live entries to make room for files that can no longer be found.
--
-- Dropping them leaves the files on disk referenced by nothing, which is precisely what a sweep
-- collects, so the next one unlinks them without being told to.  A cache is the one thing that
-- costs nothing to lose -- everything in it can be fetched again.
--
-- Display pictures need no equivalent: they have no rows, and the sweep already keeps only what
-- some `accounts.profile_pic_url` still hashes to, which under the new key is none of the old
-- ones.
DELETE FROM attachment_cache;
