-- When the *recipient* of a message last saved one of its attachments.
--
-- One column rather than two, because the two cases are the same fact seen from opposite ends: on
-- an incoming attachment the recipient is us, so this is when we last wrote it to disk; on an
-- outgoing one the recipient is the other party, so this is when they last told us they saved it.
-- Neither reading is direction-specific -- "the recipient saved this, then" -- so nothing here
-- depends on `messages.outgoing` to be understood.
--
-- Deliberately not a path.  Where a file went is the application's business: it chose the location,
-- it can move the file afterwards, and a path recorded here would be wrong the moment it did.  What
-- an application actually needs is whether there is any point offering "save" again, and that is
-- answered by a timestamp.  It is a record of an event, not a claim about the filesystem: "this was
-- saved, then" stays true after the file is deleted.
--
-- Overwritten rather than accumulated: saving twice leaves the later time, and a peer who saves the
-- same file repeatedly leaves their latest.  A history of saves is not something any client has
-- asked for, and it would be a table rather than a column.
--
-- The outgoing case can only ever be as good as what the other end sends.  It is set from a
-- DataExtractionNotification, which is voluntary -- a client that sends none, or one too old to
-- identify which message it means, leaves this NULL forever.  So NULL means "not known to have been
-- saved", never "not saved", and an application showing it must not present the absence as evidence.
ALTER TABLE message_attachments ADD COLUMN saved_at INTEGER;
