-- What the last attempt to fetch this file found, when what it found was that it could not be
-- fetched: the file server answered that it does not hold it -- which is also how an expired upload
-- answers -- or the bytes arrived and failed to authenticate.
--
-- A cached answer rather than a fact about the url, which is the distinction that decides its
-- lifetime.  An attachment url is a hash of the encrypted body, and the encryption is
-- deterministic, so the same file sent again by the same account lands at the *same* url.  That is
-- the repair path: the recipient is told the file could not be fetched, asks for it again, and the
-- sender's re-upload puts those bytes back where they were.  A flag that never cleared would block
-- exactly the action that fixes the problem.
--
-- So it is set across every row naming a url when a fetch of it fails, and cleared across every row
-- naming that url when a new attachment row quoting it arrives -- a resend being the only evidence
-- available that the server holds it again.  Cleared for the old rows too, not just the new one: it
-- is the same file, and a transcript showing one message's copy as broken and another's as fine
-- would be showing the same bytes two ways.
--
-- The value is *why*, not merely that: the file server's status for a server answer -- 404 for an
-- upload it does not hold, expired or otherwise -- and `ATTACHMENT_UNREADABLE` for bytes that
-- arrived and could not be turned back into the file they claimed to be.  A display says different
-- things to the user about those, and "ask them to send it again" is only right for the first.
--
-- NULL means only that nothing has proved otherwise: an attachment nobody has tried to fetch is
-- indistinguishable from one that will succeed.
ALTER TABLE message_attachments ADD COLUMN unavailable INTEGER;
