// Generated by gen_debug_print.py from the .proto files; do not edit.
// Regenerate with the `regen-protobuf` build target.

#pragma once

#include <SessionProtos.pb.h>
#include <WebSocketResources.pb.h>

#include <string>

namespace session::proto {

/// Renders a protobuf message as indented text: one line per field that is set, named, with nested
/// messages indented beneath their field and enums by name rather than number.
///
/// What `TextFormat` would give you if these schemas were not LITE_RUNTIME.  They are, so their
/// generated C++ has no descriptors and no reflection to build this on; it is generated from the
/// same descriptors protoc already emits, and so cannot fall behind the schema.
///
/// Fields this build does not model are not lost -- lite messages keep them as raw bytes -- but
/// they can only be reported as `<unknown fields>` and a length, since naming them is exactly what
/// the missing descriptors would have done.
std::string debug_print(const SessionProtos::Envelope& m);
std::string debug_print(const SessionProtos::TypingMessage& m);
std::string debug_print(const SessionProtos::UnsendRequest& m);
std::string debug_print(const SessionProtos::MessageRequestResponse& m);
std::string debug_print(const SessionProtos::Content& m);
std::string debug_print(const SessionProtos::CallMessage& m);
std::string debug_print(const SessionProtos::DataExtractionNotification& m);
std::string debug_print(const SessionProtos::LokiProfile& m);
std::string debug_print(const SessionProtos::DataMessage& m);
std::string debug_print(const SessionProtos::DataMessage_Quote& m);
std::string debug_print(const SessionProtos::DataMessage_Quote_QuotedAttachment& m);
std::string debug_print(const SessionProtos::DataMessage_Preview& m);
std::string debug_print(const SessionProtos::DataMessage_Reaction& m);
std::string debug_print(const SessionProtos::DataMessage_OpenGroupInvitation& m);
std::string debug_print(const SessionProtos::ReceiptMessage& m);
std::string debug_print(const SessionProtos::AttachmentPointer& m);
std::string debug_print(const SessionProtos::SharedConfigMessage& m);
std::string debug_print(const SessionProtos::GroupUpdateMessage& m);
std::string debug_print(const SessionProtos::GroupUpdateInviteMessage& m);
std::string debug_print(const SessionProtos::GroupUpdatePromoteMessage& m);
std::string debug_print(const SessionProtos::GroupUpdateInfoChangeMessage& m);
std::string debug_print(const SessionProtos::GroupUpdateMemberChangeMessage& m);
std::string debug_print(const SessionProtos::GroupUpdateMemberLeftMessage& m);
std::string debug_print(const SessionProtos::GroupUpdateMemberLeftNotificationMessage& m);
std::string debug_print(const SessionProtos::GroupUpdateInviteResponseMessage& m);
std::string debug_print(const SessionProtos::GroupUpdateDeleteMemberContentMessage& m);
std::string debug_print(const SessionProtos::ProProof& m);
std::string debug_print(const SessionProtos::ProMessage& m);
std::string debug_print(const WebSocketProtos::WebSocketRequestMessage& m);
std::string debug_print(const WebSocketProtos::WebSocketResponseMessage& m);
std::string debug_print(const WebSocketProtos::WebSocketMessage& m);

}  // namespace session::proto
