// Generated by gen_debug_print.py from the .proto files; do not edit.
// Regenerate with the `regen-protobuf` build target.

#include "debug_print.hpp"

#include <session/format.hpp>

namespace session::proto {

namespace {

// Printable ASCII through, everything else escaped: a dump of what is in the field is more use here
// than a guess at what it was meant to say.
std::string quote(std::string_view s) {
    std::string out;
    out.reserve(s.size() + 2);
    out += '"';
    for (unsigned char c : s) {
        switch (c) {
            case '"': out += "\\\""; break;
            case '\\': out += "\\\\"; break;
            case '\n': out += "\\n"; break;
            case '\r': out += "\\r"; break;
            case '\t': out += "\\t"; break;
            default:
                if (c >= 0x20 && c < 0x7f)
                    out += static_cast<char>(c);
                else
                    out += fmt::format("\\x{:02x}", c);
        }
    }
    out += '"';
    return out;
}

// Summarised past this, because a dump is for reading and a thumbnail is not.
constexpr size_t BYTES_SHOWN = 32;

std::string hex(std::string_view s) {
    auto shown = s.substr(0, BYTES_SHOWN);
    return fmt::format(
            "({} bytes) {}{}",
            s.size(),
            oxenc::to_hex(shown.begin(), shown.end()),
            s.size() > BYTES_SHOWN ? "..." : "");
}

// The field number goes in beside the name because this is a view of the wire, and the number is
// what the wire actually carries -- it is what you compare against a capture, another client's
// output, or the .proto itself.
void line(std::string& out, int depth, std::string_view name, int number, std::string_view value) {
    fmt::format_to(
            std::back_inserter(out), "{:{}}{} [{}]: {}\n", "", depth * 2, name, number, value);
}

// A nested message brackets its fields, the way protobuf's own text format does: the opening brace
// ends the field's line and the closing one sits back at the field's indent.  No colon before it --
// that is what distinguishes "here comes a block" from "here is a value".
void open_msg(std::string& out, int depth, std::string_view name, int number) {
    fmt::format_to(std::back_inserter(out), "{:{}}{} [{}] {{\n", "", depth * 2, name, number);
}

void close_msg(std::string& out, int depth) {
    fmt::format_to(std::back_inserter(out), "{:{}}}}\n", "", depth * 2);
}

// Anything this build does not model.  Lite messages keep unknown fields as raw bytes rather than
// discarding them, so we can at least say that something newer arrived and how much of it there was
// -- naming it is precisely what the descriptors we do not have would have done.
void unknown(std::string& out, int depth, const std::string& raw) {
    if (!raw.empty())
        fmt::format_to(
                std::back_inserter(out),
                "{:{}}<unknown fields>: {}\n",
                "",
                depth * 2,
                hex(raw));
}

void print(const SessionProtos::Envelope& m, std::string& out, int depth);
void print(const SessionProtos::TypingMessage& m, std::string& out, int depth);
void print(const SessionProtos::UnsendRequest& m, std::string& out, int depth);
void print(const SessionProtos::MessageRequestResponse& m, std::string& out, int depth);
void print(const SessionProtos::Content& m, std::string& out, int depth);
void print(const SessionProtos::CallMessage& m, std::string& out, int depth);
void print(const SessionProtos::DataExtractionNotification& m, std::string& out, int depth);
void print(const SessionProtos::LokiProfile& m, std::string& out, int depth);
void print(const SessionProtos::DataMessage& m, std::string& out, int depth);
void print(const SessionProtos::DataMessage_Quote& m, std::string& out, int depth);
void print(const SessionProtos::DataMessage_Quote_QuotedAttachment& m, std::string& out, int depth);
void print(const SessionProtos::DataMessage_Preview& m, std::string& out, int depth);
void print(const SessionProtos::DataMessage_Reaction& m, std::string& out, int depth);
void print(const SessionProtos::DataMessage_OpenGroupInvitation& m, std::string& out, int depth);
void print(const SessionProtos::ReceiptMessage& m, std::string& out, int depth);
void print(const SessionProtos::AttachmentPointer& m, std::string& out, int depth);
void print(const SessionProtos::SharedConfigMessage& m, std::string& out, int depth);
void print(const SessionProtos::GroupUpdateMessage& m, std::string& out, int depth);
void print(const SessionProtos::GroupUpdateInviteMessage& m, std::string& out, int depth);
void print(const SessionProtos::GroupUpdatePromoteMessage& m, std::string& out, int depth);
void print(const SessionProtos::GroupUpdateInfoChangeMessage& m, std::string& out, int depth);
void print(const SessionProtos::GroupUpdateMemberChangeMessage& m, std::string& out, int depth);
void print(const SessionProtos::GroupUpdateMemberLeftMessage& m, std::string& out, int depth);
void print(const SessionProtos::GroupUpdateMemberLeftNotificationMessage& m, std::string& out, int depth);
void print(const SessionProtos::GroupUpdateInviteResponseMessage& m, std::string& out, int depth);
void print(const SessionProtos::GroupUpdateDeleteMemberContentMessage& m, std::string& out, int depth);
void print(const SessionProtos::ProProof& m, std::string& out, int depth);
void print(const SessionProtos::ProMessage& m, std::string& out, int depth);
void print(const WebSocketProtos::WebSocketRequestMessage& m, std::string& out, int depth);
void print(const WebSocketProtos::WebSocketResponseMessage& m, std::string& out, int depth);
void print(const WebSocketProtos::WebSocketMessage& m, std::string& out, int depth);

void print(const SessionProtos::Envelope& m, std::string& out, int depth) {
    if (m.has_type())
        line(out, depth, "type", 1,Envelope_Type_Name(m.type()));
    if (m.has_source())
        line(out, depth, "source", 2,quote(m.source()));
    if (m.has_sourcedevice())
        line(out, depth, "sourceDevice", 7,fmt::format("{}", m.sourcedevice()));
    if (m.has_timestamp())
        line(out, depth, "timestamp", 5,fmt::format("{}", m.timestamp()));
    if (m.has_content())
        line(out, depth, "content", 8,hex(m.content()));
    if (m.has_servertimestamp())
        line(out, depth, "serverTimestamp", 10,fmt::format("{}", m.servertimestamp()));
    if (m.has_prosig())
        line(out, depth, "proSig", 11,hex(m.prosig()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::TypingMessage& m, std::string& out, int depth) {
    if (m.has_timestamp())
        line(out, depth, "timestamp", 1,fmt::format("{}", m.timestamp()));
    if (m.has_action())
        line(out, depth, "action", 2,TypingMessage_Action_Name(m.action()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::UnsendRequest& m, std::string& out, int depth) {
    if (m.has_msgtimestamp())
        line(out, depth, "msgTimestamp", 1,fmt::format("{}", m.msgtimestamp()));
    if (m.has_author())
        line(out, depth, "author", 2,quote(m.author()));
    if (m.has_msgid())
        line(out, depth, "msgId", 3,fmt::format("{}", m.msgid()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::MessageRequestResponse& m, std::string& out, int depth) {
    if (m.has_isapproved())
        line(out, depth, "isApproved", 1,(m.isapproved() ? "true" : "false"));
    if (m.has_profilekey())
        line(out, depth, "profileKey", 2,hex(m.profilekey()));
    if (m.has_profile()) {
        open_msg(out, depth, "profile", 3);
        print(m.profile(), out, depth + 1);
        close_msg(out, depth);
    }
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::Content& m, std::string& out, int depth) {
    if (m.has_datamessage()) {
        open_msg(out, depth, "dataMessage", 1);
        print(m.datamessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_callmessage()) {
        open_msg(out, depth, "callMessage", 3);
        print(m.callmessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_receiptmessage()) {
        open_msg(out, depth, "receiptMessage", 5);
        print(m.receiptmessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_typingmessage()) {
        open_msg(out, depth, "typingMessage", 6);
        print(m.typingmessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_dataextractionnotification()) {
        open_msg(out, depth, "dataExtractionNotification", 8);
        print(m.dataextractionnotification(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_unsendrequest()) {
        open_msg(out, depth, "unsendRequest", 9);
        print(m.unsendrequest(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_messagerequestresponse()) {
        open_msg(out, depth, "messageRequestResponse", 10);
        print(m.messagerequestresponse(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_sharedconfigmessage()) {
        open_msg(out, depth, "sharedConfigMessage", 11);
        print(m.sharedconfigmessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_expirationtype())
        line(out, depth, "expirationType", 12,Content_ExpirationType_Name(m.expirationtype()));
    if (m.has_expirationtimer())
        line(out, depth, "expirationTimer", 13,fmt::format("{}", m.expirationtimer()));
    if (m.has_sigtimestamp())
        line(out, depth, "sigTimestamp", 15,fmt::format("{}", m.sigtimestamp()));
    if (m.has_promessage()) {
        open_msg(out, depth, "proMessage", 16);
        print(m.promessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_prosigforcommunitymessageonly())
        line(out, depth, "proSigForCommunityMessageOnly", 17,hex(m.prosigforcommunitymessageonly()));
    if (m.has_msgid())
        line(out, depth, "msgId", 18,fmt::format("{}", m.msgid()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::CallMessage& m, std::string& out, int depth) {
    if (m.has_type())
        line(out, depth, "type", 1,CallMessage_Type_Name(m.type()));
    for (const auto& v : m.sdps())
        line(out, depth, "sdps", 2,quote(v));
    for (const auto& v : m.sdpmlineindexes())
        line(out, depth, "sdpMLineIndexes", 3,fmt::format("{}", v));
    for (const auto& v : m.sdpmids())
        line(out, depth, "sdpMids", 4,quote(v));
    if (m.has_uuid())
        line(out, depth, "uuid", 5,quote(m.uuid()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::DataExtractionNotification& m, std::string& out, int depth) {
    if (m.has_type())
        line(out, depth, "type", 1,DataExtractionNotification_Type_Name(m.type()));
    if (m.has_timestamp())
        line(out, depth, "timestamp", 2,fmt::format("{}", m.timestamp()));
    if (m.has_msgtimestamp())
        line(out, depth, "msgTimestamp", 3,fmt::format("{}", m.msgtimestamp()));
    if (m.has_msgid())
        line(out, depth, "msgId", 4,fmt::format("{}", m.msgid()));
    if (m.has_attindex())
        line(out, depth, "attIndex", 5,fmt::format("{}", m.attindex()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::LokiProfile& m, std::string& out, int depth) {
    if (m.has_displayname())
        line(out, depth, "displayName", 1,quote(m.displayname()));
    if (m.has_profilepicture())
        line(out, depth, "profilePicture", 2,quote(m.profilepicture()));
    if (m.has_lastupdateseconds())
        line(out, depth, "lastUpdateSeconds", 3,fmt::format("{}", m.lastupdateseconds()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::DataMessage& m, std::string& out, int depth) {
    if (m.has_body())
        line(out, depth, "body", 1,quote(m.body()));
    for (const auto& v : m.attachments()) {
        open_msg(out, depth, "attachments", 2);
        print(v, out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_flags())
        line(out, depth, "flags", 4,fmt::format("{}", m.flags()));
    if (m.has_profilekey())
        line(out, depth, "profileKey", 6,hex(m.profilekey()));
    if (m.has_timestamp())
        line(out, depth, "timestamp", 7,fmt::format("{}", m.timestamp()));
    if (m.has_quote()) {
        open_msg(out, depth, "quote", 8);
        print(m.quote(), out, depth + 1);
        close_msg(out, depth);
    }
    for (const auto& v : m.preview()) {
        open_msg(out, depth, "preview", 10);
        print(v, out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_reaction()) {
        open_msg(out, depth, "reaction", 11);
        print(m.reaction(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_profile()) {
        open_msg(out, depth, "profile", 101);
        print(m.profile(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_opengroupinvitation()) {
        open_msg(out, depth, "openGroupInvitation", 102);
        print(m.opengroupinvitation(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_synctarget())
        line(out, depth, "syncTarget", 105,quote(m.synctarget()));
    if (m.has_blockscommunitymessagerequests())
        line(out, depth, "blocksCommunityMessageRequests", 106,(m.blockscommunitymessagerequests() ? "true" : "false"));
    if (m.has_groupupdatemessage()) {
        open_msg(out, depth, "groupUpdateMessage", 120);
        print(m.groupupdatemessage(), out, depth + 1);
        close_msg(out, depth);
    }
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::DataMessage_Quote& m, std::string& out, int depth) {
    if (m.has_msgtimestamp())
        line(out, depth, "msgTimestamp", 1,fmt::format("{}", m.msgtimestamp()));
    if (m.has_author())
        line(out, depth, "author", 2,quote(m.author()));
    if (m.has_text())
        line(out, depth, "text", 3,quote(m.text()));
    for (const auto& v : m.attachments()) {
        open_msg(out, depth, "attachments", 4);
        print(v, out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_msgid())
        line(out, depth, "msgId", 5,fmt::format("{}", m.msgid()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::DataMessage_Quote_QuotedAttachment& m, std::string& out, int depth) {
    if (m.has_contenttype())
        line(out, depth, "contentType", 1,quote(m.contenttype()));
    if (m.has_filename())
        line(out, depth, "fileName", 2,quote(m.filename()));
    if (m.has_thumbnail()) {
        open_msg(out, depth, "thumbnail", 3);
        print(m.thumbnail(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_flags())
        line(out, depth, "flags", 4,fmt::format("{}", m.flags()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::DataMessage_Preview& m, std::string& out, int depth) {
    if (m.has_url())
        line(out, depth, "url", 1,quote(m.url()));
    if (m.has_title())
        line(out, depth, "title", 2,quote(m.title()));
    if (m.has_image()) {
        open_msg(out, depth, "image", 3);
        print(m.image(), out, depth + 1);
        close_msg(out, depth);
    }
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::DataMessage_Reaction& m, std::string& out, int depth) {
    if (m.has_msgtimestamp())
        line(out, depth, "msgTimestamp", 1,fmt::format("{}", m.msgtimestamp()));
    if (m.has_author())
        line(out, depth, "author", 2,quote(m.author()));
    if (m.has_emoji())
        line(out, depth, "emoji", 3,quote(m.emoji()));
    if (m.has_action())
        line(out, depth, "action", 4,DataMessage_Reaction_Action_Name(m.action()));
    if (m.has_msgid())
        line(out, depth, "msgId", 5,fmt::format("{}", m.msgid()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::DataMessage_OpenGroupInvitation& m, std::string& out, int depth) {
    if (m.has_url())
        line(out, depth, "url", 1,quote(m.url()));
    if (m.has_name())
        line(out, depth, "name", 3,quote(m.name()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::ReceiptMessage& m, std::string& out, int depth) {
    if (m.has_type())
        line(out, depth, "type", 1,ReceiptMessage_Type_Name(m.type()));
    for (const auto& v : m.timestamp())
        line(out, depth, "timestamp", 2,fmt::format("{}", v));
    for (const auto& v : m.msgid())
        line(out, depth, "msgId", 3,fmt::format("{}", v));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::AttachmentPointer& m, std::string& out, int depth) {
    if (m.has_id())
        line(out, depth, "id", 1,fmt::format("{}", m.id()));
    if (m.has_contenttype())
        line(out, depth, "contentType", 2,quote(m.contenttype()));
    if (m.has_key())
        line(out, depth, "key", 3,hex(m.key()));
    if (m.has_size())
        line(out, depth, "size", 4,fmt::format("{}", m.size()));
    if (m.has_thumbnail())
        line(out, depth, "thumbnail", 5,hex(m.thumbnail()));
    if (m.has_digest())
        line(out, depth, "digest", 6,hex(m.digest()));
    if (m.has_filename())
        line(out, depth, "fileName", 7,quote(m.filename()));
    if (m.has_flags())
        line(out, depth, "flags", 8,fmt::format("{}", m.flags()));
    if (m.has_width())
        line(out, depth, "width", 9,fmt::format("{}", m.width()));
    if (m.has_height())
        line(out, depth, "height", 10,fmt::format("{}", m.height()));
    if (m.has_caption())
        line(out, depth, "caption", 11,quote(m.caption()));
    if (m.has_url())
        line(out, depth, "url", 101,quote(m.url()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::SharedConfigMessage& m, std::string& out, int depth) {
    if (m.has_kind())
        line(out, depth, "kind", 1,SharedConfigMessage_Kind_Name(m.kind()));
    if (m.has_seqno())
        line(out, depth, "seqno", 2,fmt::format("{}", m.seqno()));
    if (m.has_data())
        line(out, depth, "data", 3,hex(m.data()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::GroupUpdateMessage& m, std::string& out, int depth) {
    if (m.has_invitemessage()) {
        open_msg(out, depth, "inviteMessage", 1);
        print(m.invitemessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_infochangemessage()) {
        open_msg(out, depth, "infoChangeMessage", 2);
        print(m.infochangemessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_memberchangemessage()) {
        open_msg(out, depth, "memberChangeMessage", 3);
        print(m.memberchangemessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_promotemessage()) {
        open_msg(out, depth, "promoteMessage", 4);
        print(m.promotemessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_memberleftmessage()) {
        open_msg(out, depth, "memberLeftMessage", 5);
        print(m.memberleftmessage(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_inviteresponse()) {
        open_msg(out, depth, "inviteResponse", 6);
        print(m.inviteresponse(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_deletemembercontent()) {
        open_msg(out, depth, "deleteMemberContent", 7);
        print(m.deletemembercontent(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_memberleftnotificationmessage()) {
        open_msg(out, depth, "memberLeftNotificationMessage", 8);
        print(m.memberleftnotificationmessage(), out, depth + 1);
        close_msg(out, depth);
    }
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::GroupUpdateInviteMessage& m, std::string& out, int depth) {
    if (m.has_groupsessionid())
        line(out, depth, "groupSessionId", 1,quote(m.groupsessionid()));
    if (m.has_name())
        line(out, depth, "name", 2,quote(m.name()));
    if (m.has_memberauthdata())
        line(out, depth, "memberAuthData", 3,hex(m.memberauthdata()));
    if (m.has_adminsignature())
        line(out, depth, "adminSignature", 4,hex(m.adminsignature()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::GroupUpdatePromoteMessage& m, std::string& out, int depth) {
    if (m.has_groupidentityseed())
        line(out, depth, "groupIdentitySeed", 1,hex(m.groupidentityseed()));
    if (m.has_name())
        line(out, depth, "name", 2,quote(m.name()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::GroupUpdateInfoChangeMessage& m, std::string& out, int depth) {
    if (m.has_type())
        line(out, depth, "type", 1,GroupUpdateInfoChangeMessage_Type_Name(m.type()));
    if (m.has_updatedname())
        line(out, depth, "updatedName", 2,quote(m.updatedname()));
    if (m.has_updatedexpiration())
        line(out, depth, "updatedExpiration", 3,fmt::format("{}", m.updatedexpiration()));
    if (m.has_adminsignature())
        line(out, depth, "adminSignature", 4,hex(m.adminsignature()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::GroupUpdateMemberChangeMessage& m, std::string& out, int depth) {
    if (m.has_type())
        line(out, depth, "type", 1,GroupUpdateMemberChangeMessage_Type_Name(m.type()));
    for (const auto& v : m.membersessionids())
        line(out, depth, "memberSessionIds", 2,quote(v));
    if (m.has_historyshared())
        line(out, depth, "historyShared", 3,(m.historyshared() ? "true" : "false"));
    if (m.has_adminsignature())
        line(out, depth, "adminSignature", 4,hex(m.adminsignature()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::GroupUpdateMemberLeftMessage& m, std::string& out, int depth) {
    (void)m;
    (void)depth;
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::GroupUpdateMemberLeftNotificationMessage& m, std::string& out, int depth) {
    (void)m;
    (void)depth;
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::GroupUpdateInviteResponseMessage& m, std::string& out, int depth) {
    if (m.has_isapproved())
        line(out, depth, "isApproved", 1,(m.isapproved() ? "true" : "false"));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::GroupUpdateDeleteMemberContentMessage& m, std::string& out, int depth) {
    for (const auto& v : m.membersessionids())
        line(out, depth, "memberSessionIds", 1,quote(v));
    for (const auto& v : m.messagehashes())
        line(out, depth, "messageHashes", 2,quote(v));
    if (m.has_adminsignature())
        line(out, depth, "adminSignature", 3,hex(m.adminsignature()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::ProProof& m, std::string& out, int depth) {
    if (m.has_version())
        line(out, depth, "version", 1,fmt::format("{}", m.version()));
    if (m.has_revocationtag())
        line(out, depth, "revocationTag", 2,hex(m.revocationtag()));
    if (m.has_rotatingpublickey())
        line(out, depth, "rotatingPublicKey", 3,hex(m.rotatingpublickey()));
    if (m.has_expiryunixts())
        line(out, depth, "expiryUnixTs", 4,fmt::format("{}", m.expiryunixts()));
    if (m.has_sig())
        line(out, depth, "sig", 5,hex(m.sig()));
    unknown(out, depth, m.unknown_fields());
}

void print(const SessionProtos::ProMessage& m, std::string& out, int depth) {
    if (m.has_proof()) {
        open_msg(out, depth, "proof", 1);
        print(m.proof(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_profilebitset())
        line(out, depth, "profileBitset", 2,fmt::format("{}", m.profilebitset()));
    if (m.has_msgbitset())
        line(out, depth, "msgBitset", 3,fmt::format("{}", m.msgbitset()));
    unknown(out, depth, m.unknown_fields());
}

void print(const WebSocketProtos::WebSocketRequestMessage& m, std::string& out, int depth) {
    if (m.has_verb())
        line(out, depth, "verb", 1,quote(m.verb()));
    if (m.has_path())
        line(out, depth, "path", 2,quote(m.path()));
    if (m.has_body())
        line(out, depth, "body", 3,hex(m.body()));
    for (const auto& v : m.headers())
        line(out, depth, "headers", 5,quote(v));
    if (m.has_requestid())
        line(out, depth, "requestId", 4,fmt::format("{}", m.requestid()));
    unknown(out, depth, m.unknown_fields());
}

void print(const WebSocketProtos::WebSocketResponseMessage& m, std::string& out, int depth) {
    if (m.has_requestid())
        line(out, depth, "requestId", 1,fmt::format("{}", m.requestid()));
    if (m.has_status())
        line(out, depth, "status", 2,fmt::format("{}", m.status()));
    if (m.has_message())
        line(out, depth, "message", 3,quote(m.message()));
    for (const auto& v : m.headers())
        line(out, depth, "headers", 5,quote(v));
    if (m.has_body())
        line(out, depth, "body", 4,hex(m.body()));
    unknown(out, depth, m.unknown_fields());
}

void print(const WebSocketProtos::WebSocketMessage& m, std::string& out, int depth) {
    if (m.has_type())
        line(out, depth, "type", 1,WebSocketMessage_Type_Name(m.type()));
    if (m.has_request()) {
        open_msg(out, depth, "request", 2);
        print(m.request(), out, depth + 1);
        close_msg(out, depth);
    }
    if (m.has_response()) {
        open_msg(out, depth, "response", 3);
        print(m.response(), out, depth + 1);
        close_msg(out, depth);
    }
    unknown(out, depth, m.unknown_fields());
}

}  // namespace

std::string debug_print(const SessionProtos::Envelope& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::TypingMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::UnsendRequest& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::MessageRequestResponse& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::Content& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::CallMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::DataExtractionNotification& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::LokiProfile& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::DataMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::DataMessage_Quote& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::DataMessage_Quote_QuotedAttachment& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::DataMessage_Preview& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::DataMessage_Reaction& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::DataMessage_OpenGroupInvitation& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::ReceiptMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::AttachmentPointer& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::SharedConfigMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::GroupUpdateMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::GroupUpdateInviteMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::GroupUpdatePromoteMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::GroupUpdateInfoChangeMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::GroupUpdateMemberChangeMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::GroupUpdateMemberLeftMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::GroupUpdateMemberLeftNotificationMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::GroupUpdateInviteResponseMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::GroupUpdateDeleteMemberContentMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::ProProof& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const SessionProtos::ProMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const WebSocketProtos::WebSocketRequestMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const WebSocketProtos::WebSocketResponseMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

std::string debug_print(const WebSocketProtos::WebSocketMessage& m) {
    std::string out;
    print(m, out, 0);
    return out;
}

}  // namespace session::proto
