#!/usr/bin/env python3
"""Generates a text dumper for the protobuf schemas, as calls to the generated accessors.

Run from the `regen-protobuf` target, alongside regenerating the .pb.cc files; the output is checked
in beside them and nothing in a normal build runs this.

The reason this is generated rather than written: SessionProtos.proto is LITE_RUNTIME, so its
generated C++ carries no descriptors, and `TextFormat` and a real `DebugString()` -- both of which
are built on reflection -- do not exist to call.  Writing the dumper by hand would work and would
silently omit every field added afterwards, which is the one thing a protocol viewer must not do.
Generating it from the same descriptors protoc already produces means it cannot fall behind the
schema: regenerate one and you regenerate the other.

Usage: protoc --descriptor_set_out=/dev/stdout foo.proto | gen_debug_print.py OUTDIR
"""

import sys

from google.protobuf import descriptor_pb2

F = descriptor_pb2.FieldDescriptorProto

# How a field's value becomes text.  `{}` is the accessor expression.
SCALAR = {
    F.TYPE_STRING: "quote({})",
    F.TYPE_BYTES: "hex({})",
    F.TYPE_BOOL: '({} ? "true" : "false")',
    F.TYPE_DOUBLE: "fmt::format(\"{{}}\", {})",
    F.TYPE_FLOAT: "fmt::format(\"{{}}\", {})",
}


def cpp_name(type_name, package):
    """".SessionProtos.DataMessage.Quote" -> "DataMessage_Quote" (nested types are flattened)."""
    stripped = type_name.lstrip(".")
    if package and stripped.startswith(package + "."):
        stripped = stripped[len(package) + 1 :]
    return stripped.replace(".", "_")


def collect(msg, prefix, out):
    full = f"{prefix}_{msg.name}" if prefix else msg.name
    out.append((full, msg))
    for nested in msg.nested_type:
        collect(nested, full, out)


def value_expr(field, expr, package):
    if field.type == F.TYPE_ENUM:
        return f"{cpp_name(field.type_name, package)}_Name({expr})"
    if field.type in SCALAR:
        return SCALAR[field.type].format(expr)
    return f'fmt::format("{{}}", {expr})'


def emit_field(w, field, package):
    # protoc lowercases a field name to make the C++ accessor, so `sourceDevice` is reached as
    # `sourcedevice()`.  The name as declared is what gets printed; the lowercased one is only ever
    # used to call the generated code.
    name = field.name.lower()
    shown = field.name
    num = field.number
    repeated = field.label == F.LABEL_REPEATED
    is_msg = field.type == F.TYPE_MESSAGE

    if repeated:
        if is_msg:
            w(f"    for (const auto& v : m.{name}()) {{\n")
            w(f'        open_msg(out, depth, "{shown}", {num});\n')
            w("        print(v, out, depth + 1);\n")
            w("        close_msg(out, depth);\n")
            w("    }\n")
        else:
            w(f"    for (const auto& v : m.{name}())\n")
            w(f'        line(out, depth, "{shown}", {num},{value_expr(field, "v", package)});\n')
        return

    if is_msg:
        w(f"    if (m.has_{name}()) {{\n")
        w(f'        open_msg(out, depth, "{shown}", {num});\n')
        w(f"        print(m.{name}(), out, depth + 1);\n")
        w("        close_msg(out, depth);\n")
        w("    }\n")
    else:
        w(f"    if (m.has_{name}())\n")
        w(
            f'        line(out, depth, "{shown}", {num},'
            f'{value_expr(field, f"m.{name}()", package)});\n'
        )


PREAMBLE = '''\
// Generated by gen_debug_print.py from the .proto files; do not edit.
// Regenerate with the `regen-protobuf` build target.

#include "debug_print.hpp"

#include <session/format.hpp>

namespace session::proto {

namespace {

// Printable ASCII through, everything else escaped: a dump of what is in the field is more use here
// than a guess at what it was meant to say.
std::string quote(std::string_view s) {
    std::string out;
    out.reserve(s.size() + 2);
    out += '"';
    for (unsigned char c : s) {
        switch (c) {
            case '"': out += "\\\\\\""; break;
            case '\\\\': out += "\\\\\\\\"; break;
            case '\\n': out += "\\\\n"; break;
            case '\\r': out += "\\\\r"; break;
            case '\\t': out += "\\\\t"; break;
            default:
                if (c >= 0x20 && c < 0x7f)
                    out += static_cast<char>(c);
                else
                    out += fmt::format("\\\\x{:02x}", c);
        }
    }
    out += '"';
    return out;
}

// Summarised past this, because a dump is for reading and a thumbnail is not.
constexpr size_t BYTES_SHOWN = 32;

std::string hex(std::string_view s) {
    auto shown = s.substr(0, BYTES_SHOWN);
    return fmt::format(
            "({} bytes) {}{}",
            s.size(),
            oxenc::to_hex(shown.begin(), shown.end()),
            s.size() > BYTES_SHOWN ? "..." : "");
}

// The field number goes in beside the name because this is a view of the wire, and the number is
// what the wire actually carries -- it is what you compare against a capture, another client's
// output, or the .proto itself.
void line(std::string& out, int depth, std::string_view name, int number, std::string_view value) {
    fmt::format_to(
            std::back_inserter(out), "{:{}}{} [{}]: {}\\n", "", depth * 2, name, number, value);
}

// A nested message brackets its fields, the way protobuf's own text format does: the opening brace
// ends the field's line and the closing one sits back at the field's indent.  No colon before it --
// that is what distinguishes "here comes a block" from "here is a value".
void open_msg(std::string& out, int depth, std::string_view name, int number) {
    fmt::format_to(std::back_inserter(out), "{:{}}{} [{}] {{\\n", "", depth * 2, name, number);
}

void close_msg(std::string& out, int depth) {
    fmt::format_to(std::back_inserter(out), "{:{}}}}\\n", "", depth * 2);
}

// Anything this build does not model.  Lite messages keep unknown fields as raw bytes rather than
// discarding them, so we can at least say that something newer arrived and how much of it there was
// -- naming it is precisely what the descriptors we do not have would have done.
void unknown(std::string& out, int depth, const std::string& raw) {
    if (!raw.empty())
        fmt::format_to(
                std::back_inserter(out),
                "{:{}}<unknown fields>: {}\\n",
                "",
                depth * 2,
                hex(raw));
}

'''


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else "."
    fds = descriptor_pb2.FileDescriptorSet.FromString(sys.stdin.buffer.read())

    files = []
    for f in fds.file:
        messages = []
        for m in f.message_type:
            collect(m, "", messages)
        files.append((f, messages))

    with open(f"{outdir}/debug_print.cpp", "w") as fh:
        w = fh.write
        w(PREAMBLE)

        for f, messages in files:
            for full, _ in messages:
                w(f"void print(const {f.package}::{full}& m, std::string& out, int depth);\n")
        w("\n")

        for f, messages in files:
            for full, msg in messages:
                w(f"void print(const {f.package}::{full}& m, std::string& out, int depth) {{\n")
                if not msg.field:
                    w("    (void)m;\n    (void)depth;\n")
                for field in msg.field:
                    emit_field(w, field, f.package)
                w("    unknown(out, depth, m.unknown_fields());\n")
                w("}\n\n")

        w("}  // namespace\n\n")

        for f, messages in files:
            for full, _ in messages:
                w(f"std::string debug_print(const {f.package}::{full}& m) {{\n")
                w("    std::string out;\n")
                w("    print(m, out, 0);\n")
                w("    return out;\n")
                w("}\n\n")

        w("}  // namespace session::proto\n")

    with open(f"{outdir}/debug_print.hpp", "w") as fh:
        w = fh.write
        w("// Generated by gen_debug_print.py from the .proto files; do not edit.\n")
        w("// Regenerate with the `regen-protobuf` build target.\n\n")
        w("#pragma once\n\n")
        for f, _ in files:
            w(f'#include <{f.name.replace(".proto", ".pb.h")}>\n')
        w("\n#include <string>\n\n")
        w("namespace session::proto {\n\n")
        w("""\
/// Renders a protobuf message as indented text: one line per field that is set, named, with nested
/// messages indented beneath their field and enums by name rather than number.
///
/// What `TextFormat` would give you if these schemas were not LITE_RUNTIME.  They are, so their
/// generated C++ has no descriptors and no reflection to build this on; it is generated from the
/// same descriptors protoc already emits, and so cannot fall behind the schema.
///
/// Fields this build does not model are not lost -- lite messages keep them as raw bytes -- but
/// they can only be reported as `<unknown fields>` and a length, since naming them is exactly what
/// the missing descriptors would have done.
""")
        for f, messages in files:
            for full, _ in messages:
                w(f"std::string debug_print(const {f.package}::{full}& m);\n")
        w("\n}  // namespace session::proto\n")


if __name__ == "__main__":
    main()
